/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import controller.CategoriaController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Categoria;
import model.DaoCategoria;

/**
 *
 * @author yulia
 */
public class CategoriaVista extends javax.swing.JFrame {

    private CategoriaController catCtrl;
    private List<Categoria> catList;
    private Categoria obj;
    
    /** Creates new form CategoriaVista */
    public CategoriaVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        //System.out.println(this.getDefaultCloseOperation()); nos devuelve un integer al abrir ventana
        this.catCtrl = new CategoriaController();
        //listar categorias a penas abra la ventana
        this.ListCategory();
    }
    
    private void ListCategory(){         
        this.catList = catCtrl.showCategory(0); 
        //usamos la instancia de la tabla
        DefaultTableModel tb =(DefaultTableModel)catListTable.getModel();
        for(Categoria cursor:this.catList){      
            //ahora debemos meter la lista a la tabla "catListTable"            
            tb.addRow(new Object[]{cursor.getId_categoria(), cursor.getCategoria()});            
        }        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddCat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catListTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelIdCat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textEditCat = new javax.swing.JTextField();
        btnSaveEditCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Categoría");

        btnAddCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnagregar.png"))); // NOI18N
        btnAddCat.setText("icon");
        btnAddCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCatMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Agregar");

        catListTable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        catListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Categoría"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catListTable.setRowHeight(35);
        catListTable.setSelectionBackground(new java.awt.Color(255, 153, 153));
        catListTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        catListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(catListTable);
        if (catListTable.getColumnModel().getColumnCount() > 0) {
            catListTable.getColumnModel().getColumn(0).setResizable(false);
            catListTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            catListTable.getColumnModel().getColumn(1).setResizable(false);
            catListTable.getColumnModel().getColumn(1).setPreferredWidth(600);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAddCat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddCat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Editar Categoría");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("ID:");

        labelIdCat.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelIdCat.setForeground(new java.awt.Color(153, 0, 0));
        labelIdCat.setText("----");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Categoría:");

        textEditCat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        btnSaveEditCat.setBackground(new java.awt.Color(153, 204, 255));
        btnSaveEditCat.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        btnSaveEditCat.setText("Guardar Cambios");
        btnSaveEditCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveEditCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveEditCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveEditCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textEditCat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(labelIdCat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEditCat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSaveEditCat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catListTableMouseClicked
              
        if(evt.getClickCount()==2){   // Este if permite el doble clic         
            //Con esto obtenemos el dato de la celda en la fila indicada
            int Fila = catListTable.getSelectedRow();
            int codigo = (int)catListTable.getValueAt(Fila, 0); //.toString()
            this.catList = this.catCtrl.showCategory(codigo);

            for(Categoria cursor:this.catList){
                //pintamos los campos
                labelIdCat.setText(String.valueOf(cursor.getId_categoria()));
                textEditCat.setText(cursor.getCategoria());
            }                             
        }
    }//GEN-LAST:event_catListTableMouseClicked

    private void cleanField(){
        labelIdCat.setText("----");
        textEditCat.setText("");
    }
    
    private void cleanTable(){
        DefaultTableModel tb =(DefaultTableModel)catListTable.getModel();         
        for(int i=tb.getRowCount()-1;i>=0;i--) 
            tb.removeRow(i);
    }
    
    private void btnSaveEditCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveEditCatActionPerformed
        // TODO add your handling code here:
        if(textEditCat.getText().isEmpty() || labelIdCat.getText() == "----"){
            JOptionPane.showMessageDialog(this, "No se puede guardar campos vacios");
            this.cleanField();
        }else{
            //mandamos los datos al controller
            this.catCtrl.editCategory(Integer.parseInt(labelIdCat.getText()), textEditCat.getText());            
            //Limpiamos campos
            this.cleanField();
            //limpiamos tabla
            this.cleanTable();
            //cargamos la tabla con los campos nuevos o modificados
            this.catCtrl = new CategoriaController();
            this.ListCategory();            
        }        
    }//GEN-LAST:event_btnSaveEditCatActionPerformed

    private void btnAddCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCatMouseClicked
        AgregarCategoria obj = new AgregarCategoria();
        obj.setVisible(true);
        this.dispose();
        //this.setEnabled(false);
    }//GEN-LAST:event_btnAddCatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAddCat;
    private javax.swing.JButton btnSaveEditCat;
    private javax.swing.JTable catListTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIdCat;
    private javax.swing.JTextField textEditCat;
    // End of variables declaration//GEN-END:variables

}
